language: node_js
env: TRAVIS_CI=true
node_js:
  - "5.9.0"
  - "7.1.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm i react@15.4.2
  - npm i react-dom@15.4.2
  - npm run test
  - npm run build